name: Sync Fork

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          owner: astral-sh
          base: main
          head: main
          token: ${{ secrets.PAT_TOKEN }}
